version: '3.3'

services:
  web:
    build:
      context: ./build
    image: nginx-php-dev:latest
    volumes:
      - ./www:/var/www/html
    ports:
      - mode: host
        target: 80
        published: 80
    links:
      - db
      - cache
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: web_db
    ports:
      - mode: host
        target: 3306
        published: 3306
  cache:
    image: redis:latest
